### PR TITLE
eXe Online

### PR DESCRIPTION
**Pull request by pedropena**

### CODE REVIEW

**Comment by JuanCasanovaSdweb** [comment]
We have decided not to merge eXeOnline into the main branch.

Development will continue as a separate branch.

**Comment by jrfern** [comment]
I suppose it's a decision taken by a development team in a space to which I don't have access, but I would like to check that you (the team) have considered the consequences: from the point of view of translators, will there be two PO files? How will the translations move from one branch to the other? Will the improvements and bug fixes in master or ws be cherry-picked or passed automatically from one branch to the other?

Saludos

**Comment by JuanCasanovaSdweb** [comment]
Hi @jrfern,
We have been discussing it for a long time. The problem is there are too many conceptual differences between the two branches, so merging them will only make the codebase a lot worse.

Any improvements or bug fixes will be made on master (unless is specific to eXeOnline) and then passed to the ws branch.

For now, the translation will be made separately. First on master, then we will merge this changes into ws and review this branch to translate any missing strings.

We will take into consideration this double translation when making any translation/launch schedule so translators don't have to do twice as much work or rush it to make it to the "deadline". Basically, we will never release a eXe version and an eXeOnline version together unless translation changes are only made on master.

Let us know if you have any other doubt, concern, etc. or if you have any ideas on how to make this process easier or more transparent for the translation team.

**Comment by jrfern** [comment]
OK. The idea seems difficult to implement, but I can't think of a better procedure if separating the two branches is considered necessary.

In my view, sorry to insist, the structure of master would need a rewriting (that nevow/twisted obsolete dependence https://docs.google.com/document/d/14_-m9FChl9sHM208oWJ95W-IEGHJw1aPqlj1vMvY2vU/edit?usp=sharing or the need to move to python3 or js https://docs.google.com/document/d/1P-gru4tePvEvpVzTaDOzxYV9wIiwQqDPdtWSUsRXfFM/edit?usp=sharing) and this is another lost chance. Anyway.

**Pull request closed without merging**
