### PR TITLE
Added some missing dependencies to build deb package

### PR DESCRIPTION
**Pull request by g-vidal**
I just tried to build deb package from sources and I had to install some python dependencies namely :
python-suds python-requests-oauthlib python-oauthlib python-requests python-blinker python-jwt python-urllib3
I have added them in the README file in installs/debian/ubuntu.

### CODE REVIEW

**Comment by jrfern** [comment]
Bon jour, @g-vidal !
I haven't been able to apply your PR because it contains two different commits and I'm only responsible for the documentation - I'm not a developer. You're right, we forgot to update the README file for installs/debian/ubuntu. But thanks to the Debian depends system, it's necessary to state fewer files than you propose. I hope it's OK now.

I fix (hopefully) the README file, but don't close the PR so @pedropena can check the development part.

Amitiés et merci beaucoup

**Comment by g-vidal** [comment]
I am very sorry I did not intend to request a pull on the second work that is not yet finished.
The important point was only on missing debian dependency packages. I'll try to remove the second commit and push it when it will be ready 
sorry again.

**Comment by jrfern** [comment]
Don't worry, you wrote it was unfinished. It's only they should have been two patches. As I have applied the first part, I would leave only or create a new one with the second section, and tell us when you have finished it.

Thank you again for everything.

**Comment by jrfern** [comment]
On 17 November 2016 at 12:35, JuanCasanovaSdweb
<notifications@github.com> wrote:
>
> Merged #63.

I don't understand this merge. This is old, README no longer exists,
and I have created a different solution for README.md that works for
me.

Could you please check it all, @JuanCasanovaSdweb ?

Saludos
-- 
Juan Rafael Fernández
http://people.ofset.org/jrfernandez/

**Pull request merged**
