### PR TITLE
update translations from transifex

### PR DESCRIPTION
**Pull request by glixx**

### CODE REVIEW

**Comment by jrfern** [comment]
Thank you, @glixx . Could you please separate the changes to exe.desktop from the changes to the RU and PL PO files?

**Comment by glixx** [comment]
I don't know how.

**Comment by jrfern** [comment]
Neither do I, unless creating a new pull request. It seems easier to use the traditional way: send me the files, and I will commit the translations and discuss with you the exe.desktop file. Is it OK with you?

**Comment by glixx** [comment]
I have no time to waist it. Just merge please.

**Comment by jrfern** [comment]
I may understand that somehow you are in a rush and will accept the request as a favour, but I still don't agree with some of the changes to exe.desktop and I haven't been able to check the new PO files, I don't know if they are correct, if they correspond to the present POT, etc. In the future please let's use the usual procedure.

**Comment by glixx** [comment]
Desktop file just has new translations and commented fields were deleted.
Translations are with according POT file.

**Comment by jrfern** [comment]
re. .desktop - It's true, I saw it when I applied the merge. The comparison of strings was confusing me.

re. POT - A newer POT was created today, if you're interested. A new iDevice is being tested.

**Comment by glixx** [comment]
Transifex updates POT file automatically by url.

**Pull request merged**
